version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
       github-actions:
          patterns: ['*']

  - package-ecosystem: "docker"
    directory: "/.github/dockerfile/"
    schedule:
      interval: "daily"
    groups:
       docker:
          patterns: ['*']
