/* Auto-generated BIF stub set — undefined-tolerant placeholders.
 * The cache tool never calls any of these; bif_table[i].f gets
 * overwritten in cache_tool_init with a sentinel that the cache
 * writer decodes back to a symbolic MFA. Stubs only need to exist
 * as link-time symbols so dyld doesn't fail at load.
 * Names defined elsewhere (external.c, erl_map.c, etc.) are
 * excluded — we link the real implementations for those. */

unsigned long abs_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long adler32_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long adler32_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long adler32_combine_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long alias_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long and_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long append_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long append_element_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long atom_to_binary_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long atom_to_list_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long atomics_add_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long atomics_add_get_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long atomics_compare_exchange_4(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long atomics_exchange_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long atomics_get_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long atomics_info_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long atomics_put_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long band_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_at_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_binary_part_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_binary_part_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_compile_pattern_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_copy_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_copy_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_decode_unsigned_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_decode_unsigned_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_encode_unsigned_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_encode_unsigned_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_first_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_last_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_list_to_bin_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_longest_common_prefix_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_longest_common_suffix_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_match_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_match_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_matches_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_matches_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_part_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_part_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_referenced_byte_size_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_split_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_split_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_to_atom_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_to_existing_atom_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_to_float_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_to_list_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long binary_to_list_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long bit_size_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long bitstring_to_list_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long bnot_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long bor_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long bsl_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long bsr_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long bump_reductions_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long bxor_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long byte_size_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long call_on_load_function_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long cancel_timer_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long cancel_timer_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ceil_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long check_old_code_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long code_coverage_support_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long code_get_coverage_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long code_get_coverage_mode_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long code_get_coverage_mode_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long code_get_debug_info_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long code_reset_coverage_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long code_set_coverage_mode_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long crc32_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long crc32_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long crc32_combine_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long date_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long decode_packet_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long delete_element_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long delete_module_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long demonitor_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long demonitor_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long display_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long display_string_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long dist_ctrl_get_data_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long dist_ctrl_get_data_notification_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long dist_ctrl_get_opt_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long dist_ctrl_input_handler_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long dist_ctrl_put_data_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long dist_ctrl_set_opt_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long dist_get_stat_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long div_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long dt_append_vm_tag_data_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long dt_get_tag_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long dt_get_tag_data_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long dt_prepend_vm_tag_data_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long dt_put_tag_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long dt_restore_tag_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long dt_spread_tag_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ebif_bang_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ebif_minusminus_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ebif_plusplus_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long element_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erase_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erase_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_ddll_demonitor_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_ddll_format_error_int_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_ddll_info_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_ddll_loaded_drivers_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_ddll_monitor_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_ddll_try_load_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_ddll_try_unload_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_debugger_breakpoint_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_debugger_breakpoints_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_debugger_breakpoints_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_debugger_instrumentations_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_debugger_peek_stack_frame_slot_4(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_debugger_peek_xreg_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_debugger_register_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_debugger_stack_frames_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_debugger_supported_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_debugger_toggle_instrumentations_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_debugger_unregister_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_debugger_whereis_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erl_debugger_xregs_count_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long error_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long error_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long error_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long error_logger_warning_map_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_debug_breakpoint_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_debug_copy_shared_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_debug_dirty_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_debug_dirty_cpu_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_debug_dirty_io_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_debug_disassemble_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_debug_flat_size_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_debug_get_internal_state_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_debug_instructions_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_debug_interpreter_size_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_debug_lcnt_clear_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_debug_lcnt_collect_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_debug_lcnt_control_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_debug_lcnt_control_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_debug_same_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_debug_set_internal_state_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_debug_size_shared_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_debug_unaligned_bitstring_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_abort_pending_connection_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_atomics_new_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_beamfile_chunk_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_beamfile_module_md5_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_binary_to_integer_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_check_dirty_process_code_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_check_process_code_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_cmp_term_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_counters_add_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_counters_get_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_counters_info_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_counters_new_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_counters_put_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_create_dist_channel_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_dirty_process_handle_signals_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_dist_spawn_request_4(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_erase_persistent_terms_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_ets_lookup_binary_info_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_ets_raw_first_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_ets_raw_next_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_ets_super_user_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_garbage_collect_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_gather_alloc_histograms_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_gather_carrier_info_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_get_creation_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_get_dflags_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_group_leader_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_group_leader_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_is_process_alive_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_is_process_executing_dirty_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_is_system_process_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_list_to_integer_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_new_connection_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_no_aux_work_threads_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_notify_breakpoint_hit_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_open_port_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_perf_counter_unit_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_port_call_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_port_close_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_port_command_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_port_connect_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_port_control_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_port_info_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_port_info_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_prepare_loading_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_process_display_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_process_flag_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_processes_next_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_purge_module_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_request_system_task_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_request_system_task_4(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_scheduler_wall_time_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_spawn_request_4(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_spawn_system_process_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_suspend_process_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_system_check_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_system_monitor_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_system_monitor_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_term_to_string_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_time_unit_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_trace_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_trace_4(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_trace_info_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_trace_pattern_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_trace_pattern_4(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_trace_session_create_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_internal_trace_session_destroy_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_literal_area_collector_release_area_switch_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_literal_area_collector_send_copy_request_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_trace_cleaner_check_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long erts_trace_cleaner_send_trace_clean_signal_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_delete_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_delete_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_delete_object_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_first_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_first_lookup_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_give_away_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_info_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_info_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_insert_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_insert_new_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_internal_delete_all_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_internal_request_all_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_internal_select_delete_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_is_compiled_ms_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_last_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_last_lookup_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_lookup_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_lookup_element_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_lookup_element_4(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_match_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_match_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_match_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_match_object_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_match_object_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_match_object_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_match_spec_compile_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_match_spec_run_r_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_member_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_new_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_next_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_next_lookup_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_prev_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_prev_lookup_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_rename_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_safe_fixtable_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_select_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_select_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_select_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_select_count_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_select_replace_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_select_reverse_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_select_reverse_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_select_reverse_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_setopts_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_slot_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_take_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_update_counter_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_update_counter_4(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_update_element_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_update_element_4(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ets_whereis_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long exit_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long exit_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long exit_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long exit_signal_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long exit_signal_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long file_native_name_encoding_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long finish_after_on_load_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long finish_loading_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long float_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long float_to_binary_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long float_to_binary_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long float_to_list_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long float_to_list_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long floor_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long fun_info_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long fun_info_mfa_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long fun_to_list_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long function_exported_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long get_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long get_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long get_keys_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long get_keys_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long get_module_info_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long get_module_info_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long group_leader_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long halt_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long has_prepared_code_on_load_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long hd_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long hibernate_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long insert_element_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long intdiv_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long integer_to_binary_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long integer_to_binary_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long integer_to_list_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long integer_to_list_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long io_printable_range_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long iolist_size_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long iolist_to_binary_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long iolist_to_iovec_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_atom_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_binary_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_bitstring_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_boolean_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_builtin_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_float_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_function_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_function_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_integer_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_integer_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_list_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_map_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_number_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_pid_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_port_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_process_alive_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_record_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_record_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_record_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_reference_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long is_tuple_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long length_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long link_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long link_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long list_to_atom_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long list_to_binary_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long list_to_bitstring_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long list_to_existing_atom_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long list_to_float_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long list_to_pid_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long list_to_port_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long list_to_ref_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long list_to_tuple_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long lists_keyfind_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long lists_keymember_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long lists_keysearch_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long lists_member_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long lists_reverse_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long load_nif_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long loaded_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long localtime_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long localtime_to_universaltime_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long make_fun_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long make_ref_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long make_tuple_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long make_tuple_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long match_spec_test_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_acos_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_acosh_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_asin_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_asinh_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_atan2_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_atan_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_atanh_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_ceil_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_cos_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_cosh_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_erf_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_erfc_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_exp_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_floor_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_fmod_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_log10_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_log2_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_log_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_pow_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_sin_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_sinh_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_sqrt_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_tan_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long math_tanh_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long max_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long md5_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long md5_final_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long md5_init_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long md5_update_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long min_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long module_loaded_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long monitor_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long monitor_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long monitor_node_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long monitor_node_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long monotonic_time_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long monotonic_time_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long net_kernel_dflag_unicode_io_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long nif_error_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long nif_error_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long node_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long node_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long nodes_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long nodes_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long nodes_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long not_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long now_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long or_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long os_env_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long os_getenv_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long os_getpid_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long os_perf_counter_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long os_putenv_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long os_set_signal_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long os_system_time_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long os_system_time_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long os_timestamp_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long os_unsetenv_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long persistent_term_erase_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long persistent_term_get_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long persistent_term_get_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long persistent_term_get_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long persistent_term_info_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long persistent_term_put_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long persistent_term_put_new_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long phash2_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long phash2_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long phash_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long pid_to_list_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long port_get_data_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long port_set_data_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long port_to_list_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ports_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long posixtime_to_universaltime_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long pre_loaded_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long prim_file_internal_name2native_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long prim_file_internal_native2name_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long prim_file_internal_normalize_utf8_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long prim_file_is_translatable_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long process_flag_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long process_info_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long process_info_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long processes_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long put_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long raise_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long re_compile_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long re_compile_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long re_import_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long re_inspect_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long re_internal_run_4(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long re_run_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long re_run_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long re_version_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long read_timer_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long read_timer_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long records_create_4(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long records_get_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long records_get_definition_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long records_get_field_names_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long records_get_module_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long records_get_name_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long records_is_exported_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long records_update_4(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long ref_to_list_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long register_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long registered_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long rem_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long resume_process_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long round_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long schedule_dirty_cpu_display_string_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long schedule_dirty_cpu_erts_debug_dirty_cpu_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long schedule_dirty_cpu_erts_debug_lcnt_clear_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long schedule_dirty_cpu_erts_debug_lcnt_collect_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long schedule_dirty_cpu_erts_debug_lcnt_control_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long schedule_dirty_io_erts_debug_dirty_io_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long self_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long send_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long send_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long send_after_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long send_after_4(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long seq_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long seq_trace_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long seq_trace_info_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long seq_trace_print_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long seq_trace_print_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long seqeq_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long setelement_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long setnode_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long sge_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long sgt_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long size_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long sle_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long slt_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long sminus_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long sminus_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long sneq_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long sneqeq_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long spawn_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long spawn_link_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long spawn_opt_4(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long spawn_request_abandon_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long split_binary_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long splus_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long splus_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long start_timer_3(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long start_timer_4(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long statistics_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long stimes_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long string_list_to_float_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long subtract_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long system_flag_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long system_info_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long system_profile_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long system_profile_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long system_time_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long system_time_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long throw_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long time_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long time_offset_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long time_offset_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long timestamp_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long tl_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long trace_delivered_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long trace_info_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long trunc_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long tuple_size_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long tuple_to_list_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long unalias_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long unicode_bin_is_7bit_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long unicode_characters_to_binary_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long unicode_characters_to_list_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long unique_integer_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long unique_integer_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long universaltime_0(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long universaltime_to_localtime_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long universaltime_to_posixtime_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long unlink_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long unregister_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long whereis_1(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
unsigned long xor_2(void *p, unsigned long *args, void *i) { (void)p; (void)args; (void)i; return 0; }
