on:
  workflow_call:
    inputs:
      BASE_BRANCH:
        required: true
        type: string
      TYPE:
        type: string
        default: '64-bit'
      USE_CACHE:
        type: boolean
        default: true
      BUILD_IMAGE:
        type: boolean
        default: false

jobs:
  build-base:
      - name: Cleanup GH Runner
        run: |
            ## Delete large files from runner to get more disk space
            ## See https://github.com/actions/runner-images/issues/2840
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf /opt/ghc
            sudo rm -rf "/usr/local/share/boost"
            sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - uses: actions/checkout@v3

      - name: Cache BASE image
        uses: actions/cache@v3
        with:
            path: otp_docker_base.tar
            key: ${{ runner.os }}-${{ hashFiles('.github/dockerfiles/Dockerfile.ubuntu-base', '.github/scripts/build-base-image.sh') }}-${{ hashFiles('OTP_VERSION') }}

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build BASE image
        run: .github/scripts/build-base-image.sh "${{ inputs.BASE_BRANCH }}" "${{ inputs.TYPE }}"

      - name: Cache pre-built tar archives
        if: inputs.BUILD_IMAGE
        uses: actions/cache@v3
        with:
            path: |
                otp_src.tar.gz
                otp_cache.tar.gz
            key: prebuilt-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
            restore-keys: |
                prebuilt-${{ github.ref_name }}-${{ github.sha }}
      - name: Build image
        if: inputs.BUILD_IMAGE
        run: |
          .github/scripts/restore-from-prebuilt.sh `pwd` .github/otp.tar.gz
          rm -f otp_{src,cache}.tar.gz
          docker build --tag otp \
            --build-arg MAKEFLAGS=-j$(($(nproc) + 2)) \
            --file ".github/dockerfiles/Dockerfile.64-bit" \
            .github/
