name: Comment on the pull request

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Build and check Erlang/OTP"]
    types:
      - requested
      - completed

jobs:
  starting-tests:
    runs-on: ubuntu-latest
    if: >-
      ${{ github.repository == 'garazdawi/otp' &&
          github.event.workflow_run.pull_requests[0] != null &&
          github.event.action == 'requested' }}
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          comment-author: 'github-actions[bot]'
          body-includes: Erlang/OTP Github Action Bot
      - uses: actions/github-script@v5
        id: failed-tests
        with:
          script: |
            const script = require('./.github/scripts/pr-comment.js');
            return await script({github, context, ''});

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        if: steps.fc.outputs.comment-id == ''
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          body: |
            ${{ fromJson(steps.failed-tests.outputs.result) }}

  finished-tests:
    runs-on: ubuntu-latest
    if: >-
      ${{ github.repository == 'garazdawi/otp' &&
          github.event.workflow_run.pull_requests[0] != null &&
          github.event.workflow_run.conclusion != 'skipped' &&
          github.event.action == 'completed' }}
    steps:
      - uses: actions/checkout@v2
      - name: Download and Extract Artifacts
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
           mkdir -p artifacts && cd artifacts

           artifacts_url=${{ github.event.workflow_run.artifacts_url }}

           gh api "$artifacts_url" --paginate -q '.artifacts[] | [.name, .archive_download_url] | @tsv' | while read artifact
           do
             IFS=$'\t' read name url <<< "$artifact"
             if [ "$name" = "Unit Test Results" ]; then
               gh api $url > "$name.zip"
               unzip -d "$name" "$name.zip"
             fi
           done

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          check_name: "CT Test Results"
          files: "artifacts/**/*.xml"

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          comment-author: 'github-actions[bot]'
          body-includes: "CT Test Results"

      - uses: actions/github-script@v5
        id: failed-tests
        with:
          script: |
            const script = require('./.github/scripts/pr-comment.js');
            return await script({github, context, '${{ steps.fc.outputs.comment-body }}'});

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          edit-mode: replace
          body: |
            ${{ fromJson(steps.failed-tests.outputs.result) }}
