name: Comment on the pull request

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Build and check Erlang/OTP"]
    types:
      - requested
      - completed

jobs:
  starting-tests:
    runs-on: ubuntu-latest
    if: >-
      ${{ github.repository == 'garazdawi/otp' &&
          github.event.workflow_run.pull_requests[0] != null &&
          github.event.action == 'requested' }}
    steps:
      - uses: actions/checkout@v2
      ## We create an initial comment with some useful help to the user
      - uses: actions/github-script@v5
        with:
          script: |
            const script = require('./.github/scripts/pr-comment.js');
            return await script({github, context});

  finished-tests:
    runs-on: ubuntu-latest
    if: >-
      ${{ github.repository == 'garazdawi/otp' &&
          github.event.workflow_run.pull_requests[0] != null &&
          github.event.workflow_run.conclusion != 'skipped' &&
          github.event.action == 'completed' }}
    steps:
      - uses: actions/checkout@v2
      - name: Download and Extract Artifacts
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
           mkdir -p artifacts && cd artifacts

           artifacts_url=${{ github.event.workflow_run.artifacts_url }}

           gh api "$artifacts_url" --paginate -q '.artifacts[] | [.name, .archive_download_url] | @tsv' | while read artifact
           do
             IFS=$'\t' read name url <<< "$artifact"
             if [ "$name" = "Unit Test Results" ] || [ "$name" = "Event File" ]; then
                   gh api $url > "$name.zip"
                   unzip -d "$name" "$name.zip"
             fi
           done

      - name: Publish CT Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          check_name: "CT Test Results"
          files: "artifacts/**/*.xml"

        ## Append some usefull links and tips to the test results posted by
        ## Publish CT Test Results
      - uses: actions/github-script@v5
        with:
          script: |
            const script = require('./.github/scripts/pr-comment.js');
            return await script({github, context });
