# %CopyrightBegin%
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright Ericsson AB 2026. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%

name: Test Erlang/OTP (Windows)

on:
  workflow_call:
    inputs:
      changes:
        required: true
        type: string
      installer_name:
        required: true
        type: string

permissions:
  contents: read

jobs:
  test-windows:
    name: Test Erlang/OTP (Windows)
    runs-on: windows-2025
    permissions:
      contents: read
      actions: write
    defaults:
      run:
        shell: wsl-bash {0}
    strategy:
      fail-fast: false
      matrix:
        type: ${{ fromJson(inputs.changes) }}
    steps:
      - name: Configure line endings for WSL
        shell: cmd
        run: git config --global core.autocrlf input

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - uses: Vampire/setup-wsl@6a8db447be7ed35f2f499c02c6e60ff77ef11278 # ratchet:Vampire/setup-wsl@v6.0.0
        with:
          distribution: Ubuntu-18.04

      - name: Install WSL dependencies
        run: apt update && apt install -y unzip

      - name: Download installer
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # ratchet:actions/download-artifact@v6.0.0
        with:
          name: otp_win32_installer

      - name: Download tests
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # ratchet:actions/download-artifact@v6.0.0
        with:
          name: otp_tests

      - name: Install Erlang/OTP
        shell: cmd
        env:
          INSTALLER_NAME: ${{ inputs.installer_name }}
        run: start "" /WAIT %INSTALLER_NAME% /S /D=%CD%\release\win32\

      - name: Run tests
        env:
          APP: ${{ matrix.type }}
        run: |
          unzip -q tests.zip
          export ERL_TOP="$(pwd)"
          eval `./otp_build env_win32 x64`
          export PATH="$(pwd)/release/win32/bin:$PATH"
          if [ "${APP}" = debug ]; then
            exit 0
          elif [ -f "release/tests/${APP}_test/${APP}_gh.spec" ]; then
            RUN_TESTS="ts:run_category(${APP},gh,[batch])"
          else
            RUN_TESTS="ts:run(${APP},[batch])"
          fi
          (cd release/tests/test_server && \
           erl.exe -noinput -eval "ts:install()" \
                   -eval "${RUN_TESTS}" -s init stop)
          ! grep -l "^=result[ ]*failed:" \
            release/tests/test_server/ct_run.*/*${APP}*.logs/run*/suite.log

      - name: Package test results
        if: ${{ !cancelled() && matrix.type != 'debug' }}
        run: tar czf ${{ matrix.type }}_win32_test_results.tar.gz release/tests/test_server

      - name: Upload test results
        if: ${{ !cancelled() && matrix.type != 'debug' }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # ratchet:actions/upload-artifact@v6.0.0
        with:
          name: ${{ matrix.type }}_win32_test_results
          path: ${{ matrix.type }}_win32_test_results.tar.gz
